In [8]:
 ### a = ['인천','부산',['전라','경상'],['대전','광주','대구'], '서울','제주']
  #  (1) '부산'부터 '대구'까지 추출
  #  (2) '대전'부터 '제주'까지 추출
   # (3) '인천'부터 '서울'까지 추출
   # (4) '광주'부터 '대구'까지 추출
""" 

SyntaxError: incomplete input (2866662356.py, line 6)

In [9]:
import pandas as pd

In [43]:
a = ['인천','부산',['전라','경상'],['대전','광주','대구'], '서울','제주']

In [44]:
a[1:4]

['부산', ['전라', '경상'], ['대전', '광주', '대구']]

In [45]:
a[3:]

[['대전', '광주', '대구'], '서울', '제주']

In [46]:
a[:5]

['인천', '부산', ['전라', '경상'], ['대전', '광주', '대구'], '서울']

In [52]:
a[3][1:3]

['광주', '대구']

In [27]:
""" [ 연습2 ]
0~20 로 채워진 4행 5열의 정수 배열 생성
"""

' [ 연습2 ]\n0~20 로 채워진 4행 5열의 정수 배열 생성\n'

In [71]:
import pandas as pd

In [72]:
import numpy as np

In [73]:
a=np.array(range(20)).reshape(4,5)
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [74]:
a, b = 3, 10
a+b

13

In [75]:
a*b

30

In [76]:
del a

In [77]:
type(b)

int

In [78]:
a, b = 10, 20

In [79]:
add = a+b
add

30

In [80]:
print('a + b = ' + str(add))

a + b = 30


In [81]:
msg = '오늘도 행복하다. 즐거운 하루~'

In [82]:
msg[4:6]

'행복'

In [83]:
a = int(input())

for i in range(1,10) : 
    print(a*i)

3
6
9
12
15
18
21
24
27


In [84]:
msg = "우리는 독도를 지킨다"

In [86]:
msg.replace("독도", "대한민국")

'우리는 대한민국를 지킨다'

In [89]:
msg.replace("우리","준성이")

'준성이는 독도를 지킨다'

In [90]:
msg.endswith('다')

True

In [91]:
msg.startswith('우')

True

In [92]:
from datetime import date
today = date.today()
today

datetime.date(2024, 6, 3)

In [94]:
print('연도 : ', today.year)
print('월 : ', today.month)
print('일 : ', today.day)
print('요일 : ', today.weekday()) # 0 : 월요일

연도 :  2024
월 :  6
일 :  3
요일 :  0


In [95]:
day = ["월요일", "화요일", "수요일", "목요일", "금요일", "토요일", "일요일"]

In [101]:
from datetime import timedelta
today = date.today()
print('어제 : ', today + timedelta(days=-1))
print('일주일 전 : ', today + timedelta(days=-7))
print('10일 후 : ', today + timedelta(days=10))

어제 :  2024-06-02
일주일 전 :  2024-05-27
10일 후 :  2024-06-13


In [102]:
from datetime import datetime
today = datetime.today()
today

datetime.datetime(2024, 6, 3, 15, 26, 21, 793643)

In [103]:
today.strftime('%m/%d/%Y')

'06/03/2024'

In [106]:
# 2024년 6월 3일 15:10:15
today.strftime('%Y년 %m월 %d일 %H:%M:%S')

'2024년 06월 03일 15:26:21'

In [112]:
# 2024-05-31 12:00:00

In [114]:
a = '2024-05-31 12:00:00'

In [115]:
type(a)

str

In [118]:
a = datetime.strptime(a, '%Y-%m-%d %H:%M:%S')

In [119]:
type(a)

datetime.datetime

In [120]:
pd.to_datetime(a)

Timestamp('2024-05-31 12:00:00')

In [1]:
a = ['독','도','는']
b = ['대한민국', '섬']

In [2]:
a + b

['독', '도', '는', '대한민국', '섬']

In [3]:
a * 3 + b 

['독', '도', '는', '독', '도', '는', '독', '도', '는', '대한민국', '섬']

In [ ]:
리스트 관련 함수들
#           append()    : 요소 추가
#           sort()      : 리스트 정렬      => 원본변경
#           reverse()   : 역순으로 뒤집기   => 원본변경
#           index()     : 위치 반환
#           insert()    : 리스트에 요소 삽입
#           remove()    : 요소 제거
#           pop()       : 맨 마지막 요소를 꺼내기
#           count()     : 요소 개수 세기
#           extend()    : 리스트에 리스트를 더하기    => 원본변경
#           clear()     : 모든 요소를 제거

In [4]:
c = [4,5,6,7,7,3,5,6,8,4,5]
# 0~10까지의 데이터에서 4 값을 77로 변경

# 5,6번째 데이터를 'k','o'로 한꺼번에 변경

In [36]:
c[0:10]

[4, 5, 6, 7, 7, 3, 5, 6, 8, 4]

In [37]:
mg = c[0:10]

In [38]:
for i in mg:
    if i == 4 :
        i = 77
print(i)

77


In [32]:
mg[4:6] = ['k', 'o']

In [33]:
mg

[4, 5, 6, 7, 'k', 'o', 5, 6, 8, 4]

In [39]:
d = {4,5,6,7,5}
e = {4,9,0,2,5,5}
d.intersection(e) # d & e

{4, 5}

In [40]:
type(d)

set

In [41]:
d.union(e)   # d | e

{0, 2, 4, 5, 6, 7, 9}

In [42]:
d-e   # 순서가 중요

{6, 7}

In [43]:
"""
    [ dictionary 형 ]

    1- 키와 값으로 구성 ( 자바의 map 와 유사 )
    2- 저장된 자료의 순서는 의미 없음 (***)
    3- 중괄호 {} 사용
    4- 변경가능

    ` 사전.keys() : key만 추출 (임의의 순서)
    ` 사전.values() : value만 추출 (임의의 순서)
    ` 사전.items() : key와 value를 튜플로 추출 (임의의 순서)
"""

'\n    [ dictionary 형 ]\n\n    1- 키와 값으로 구성 ( 자바의 map 와 유사 )\n    2- 저장된 자료의 순서는 의미 없음 (***)\n    3- 중괄호 {} 사용\n    4- 변경가능\n\n    ` 사전.keys() : key만 추출 (임의의 순서)\n    ` 사전.values() : value만 추출 (임의의 순서)\n    ` 사전.items() : key와 value를 튜플로 추출 (임의의 순서)\n'

In [47]:
dt = {1:'one', 2:'two', '3':'three'}
dt

{1: 'one', 2: 'two', '3': 'three'}

In [48]:
dt[2]

'two'

In [49]:
dt['3']

'three'

In [50]:
dt[3] = 'three'

In [51]:
dt

{1: 'one', 2: 'two', '3': 'three', 3: 'three'}

In [53]:
dt['korea'] = 'seoul'
dt

{1: 'one', 2: 'two', '3': 'three', 3: 'three', 'korea': 'seoul'}

In [54]:
dt.update({3:'nam', '3':'kim'})

In [55]:
dt

{1: 'one', 2: 'two', '3': 'kim', 3: 'nam', 'korea': 'seoul'}

In [56]:
dt.keys()

dict_keys([1, 2, '3', 3, 'korea'])

In [57]:
dt.values()

dict_values(['one', 'two', 'kim', 'nam', 'seoul'])

In [58]:
dt.items()

dict_items([(1, 'one'), (2, 'two'), ('3', 'kim'), (3, 'nam'), ('korea', 'seoul')])